### ISSUE TITLE
Projects displayed in sidebar

### ISSUE THREAD

**Issue by clousea14** [yebuahk/2ptracker#14]
I am creating some decision tables, and I was trying to make sure I understand everything we discussed as far as the project list in the sidebar is concerned. Is this list going to be a cumulative list of every project that the company has created, or is it going to be specific to the user and only display those projects which s/he has created or been assigned to?

Sorry, I know we addressed this during our last meeting, but I am just verifying that it is the former rather than the latter.

There are a few things I would recommend we change if we had more time. I think it should be only the projects that a user is associated with, but based on the time constraints I don't blame anyone for us going with the easier of the two options. Hopefully Dr. Barb doesn't question it.

**Comment by yebuahk** [comment]
It is going to be cumulative list of every project that the company has created.

**Comment by clousea14** [comment]
Thanks for verifying.
